This file takes in colin's data.zip from 05/03 and adds hyunwoo's fingerprint.

In [1]:
import glob, numpy as np, os, shutil, pickle, rdkit, sys, tqdm, fingerprint_utils, torch
assert(os.path.exists("../../tempdata/data"))

Creating hyun_fp_data

In [5]:
def shatter(shatter_dir, obj, id, keys):
    '''
        Saves an object as individual files
    '''
    for key in keys:
        elem = obj[key]
        if type(elem) == np.ndarray:
            torch.save(torch.tensor(elem, dtype=torch.float), f"{shatter_dir}/{key}/{id}.pt")
        elif type(elem) == str:
            torch.save(elem, f"{shatter_dir}/{key}/{id}.pt")


In [ ]:
files = glob.glob("../../tempdata/data/*/*.pkl")
out_dir = "../../tempdata/hyun_fp_data"
os.makedirs(out_dir, exist_ok=True)
save_attrs = {
    "hsqc_ms_pairs": ["SMILES", "FP", "HYUN_FP", "HSQC", "MS"],
    "hsqc_pretrain": ["SMILES", "FP", "HYUN_FP", "HSQC"],
    "ms_pretrain": ["SMILES", "FP", "HYUN_FP", "MS"]
}
for file_path in files:
    subdivision = file_path.split("/")[-2]
    split = file_path.split("/")[-1]
    split = split[:split.index(".")]

    for my_attr in save_attrs[subdivision]:
        os.makedirs(f"{out_dir}/{subdivision}/{split}/{my_attr}", exist_ok=True)

    print(file_path, subdivision, split)
    with open(file_path, "rb") as f:
        obj = pickle.load(f)

    keys = set(obj.keys())
    for k in keys:
        v = obj[k]
        v["HYUN_FP"] = fingerprint_utils.FP_generator(v["SMILES"], 2)
        shatter(f"{out_dir}/{subdivision}/{split}", v, k, save_attrs[subdivision])
        del obj[k]

In [ ]:
for f in os.listdir(out_dir):
    for g in os.listdir(os.path.join(out_dir, f)):
        print(f"{f}/{g}/{len(os.listdir(os.path.join(out_dir, f, g, 'FP')))}")

New Dataset using better bounds / hsqc intensity rounding

In [ ]:
v = torch.randint(-10, 10, (30, 50, 3)).float()
v[:,:,2] = torch.where(v[:,:,2] >= 0, 1.0, -1.0)

In [27]:
files = glob.glob("../../tempdata/data/*/*.pkl")
out_dir = "../../tempdata/bounded_hyun_fp_data"
os.makedirs(out_dir, exist_ok=True)

save_attrs = {
    "hsqc_ms_pairs": ["SMILES", "FP", "HYUN_FP", "HSQC", "MS"],
    "hsqc_pretrain": ["SMILES", "FP", "HYUN_FP", "HSQC"],
    "ms_pretrain": ["SMILES", "FP", "HYUN_FP", "MS"]
}

for file_path in files:
    subdivision = file_path.split("/")[-2]
    split = file_path.split("/")[-1]
    split = split[:split.index(".")]

    for my_attr in save_attrs[subdivision]:
        os.makedirs(f"{out_dir}/{subdivision}/{split}/{my_attr}", exist_ok=True)

    print(file_path, subdivision, split)
    with open(file_path, "rb") as f:
        obj = pickle.load(f)

    keys = set(obj.keys())
    print(save_attrs[subdivision])
    for k in keys:
        v = obj[k]
        v["HYUN_FP"] = fingerprint_utils.FP_generator(v["SMILES"], 2)
        shatter2(f"{out_dir}/{subdivision}/{split}", v, k, save_attrs[subdivision])
        del obj[k]

../../tempdata/data/hsqc_ms_pairs/train.pkl hsqc_ms_pairs train
['SMILES', 'FP', 'HYUN_FP', 'HSQC', 'MS']


[03:29:51] WARNING: not removing hydrogen atom without neighbors


../../tempdata/data/hsqc_ms_pairs/val.pkl hsqc_ms_pairs val
['SMILES', 'FP', 'HYUN_FP', 'HSQC', 'MS']
../../tempdata/data/hsqc_ms_pairs/test.pkl hsqc_ms_pairs test
['SMILES', 'FP', 'HYUN_FP', 'HSQC', 'MS']
../../tempdata/data/hsqc_pretrain/train.pkl hsqc_pretrain train
['SMILES', 'FP', 'HYUN_FP', 'HSQC']


[03:31:20] WARNING: not removing hydrogen atom without neighbors
[03:31:28] WARNING: not removing hydrogen atom without neighbors
[03:31:32] WARNING: not removing hydrogen atom without neighbors
[03:31:55] WARNING: not removing hydrogen atom without neighbors
[03:32:06] WARNING: not removing hydrogen atom without neighbors
[03:33:18] WARNING: not removing hydrogen atom without neighbors
[03:34:02] WARNING: not removing hydrogen atom without neighbors
[03:35:41] WARNING: not removing hydrogen atom without neighbors
[03:36:27] WARNING: not removing hydrogen atom without neighbors
[03:37:54] WARNING: not removing hydrogen atom without neighbors


../../tempdata/data/hsqc_pretrain/val.pkl hsqc_pretrain val
['SMILES', 'FP', 'HYUN_FP', 'HSQC']


[03:39:11] WARNING: not removing hydrogen atom without neighbors
[03:39:30] WARNING: not removing hydrogen atom without neighbors


../../tempdata/data/hsqc_pretrain/test.pkl hsqc_pretrain test
['SMILES', 'FP', 'HYUN_FP', 'HSQC']


[03:40:11] WARNING: not removing hydrogen atom without neighbors
[03:40:11] WARNING: not removing hydrogen atom without neighbors


../../tempdata/data/ms_pretrain/train.pkl ms_pretrain train
['SMILES', 'FP', 'HYUN_FP', 'MS']
../../tempdata/data/ms_pretrain/val.pkl ms_pretrain val
['SMILES', 'FP', 'HYUN_FP', 'MS']
../../tempdata/data/ms_pretrain/test.pkl ms_pretrain test
['SMILES', 'FP', 'HYUN_FP', 'MS']


In [15]:
for f in os.listdir(out_dir):
    for g in os.listdir(os.path.join(out_dir, f)):
        print(f"{f}/{g}/{len(os.listdir(os.path.join(out_dir, f, g, 'FP')))}")

hsqc_ms_pairs/train/1


Creating same dataset, but using hsqc as images

In [ ]:
# @wangdong make sure you pull colin_split_05_23_22.zip before running this code
# this creates the pickle files into ../../tempdata/data/...
def shatter(shatter_dir, obj, id, keys):
    '''
        Saves an object as individual files
    '''
    for key in keys:
        elem = obj[key]
        if type(elem) == np.ndarray:
            if key == "HSQC":
                # @wangdong you can add handler functions here to pre-process your data
                elem2 = elem
                torch.save(elem2, f"{shatter_dir}/{key}/{id}.pt")
                pass
            else:
                torch.save(torch.tensor(elem, dtype=torch.float), f"{shatter_dir}/{key}/{id}.pt")
        elif type(elem) == str:
            torch.save(elem, f"{shatter_dir}/{key}/{id}.pt")

files = glob.glob("../../tempdata/data/*/*.pkl") # colin's input
output_dir_name = None # @wandong change the output directory here
assert(output_dir_name)
out_dir = f"../../tempdata/{output_dir_name}"
os.makedirs(out_dir, exist_ok=True)
save_attrs = {
    "hsqc_ms_pairs": ["SMILES", "FP", "HYUN_FP", "HSQC", "MS"],
    "hsqc_pretrain": ["SMILES", "FP", "HYUN_FP", "HSQC"],
    "ms_pretrain": ["SMILES", "FP", "HYUN_FP", "MS"]
}
for file_path in files:
    subdivision = file_path.split("/")[-2]
    split = file_path.split("/")[-1]
    split = split[:split.index(".")]

    for my_attr in save_attrs[subdivision]:
        os.makedirs(f"{out_dir}/{subdivision}/{split}/{my_attr}", exist_ok=True)

    print(file_path, subdivision, split)
    with open(file_path, "rb") as f:
        obj = pickle.load(f)

    keys = set(obj.keys())
    for k in keys:
        v = obj[k] # the object that you want to split into directories
        v["HYUN_FP"] = fingerprint_utils.FP_generator(v["SMILES"], 2)
        shatter(f"{out_dir}/{subdivision}/{split}", v, k, save_attrs[subdivision])
        del obj[k]

10/25/22: We were advised from 10/20 NIH meeting to only use 10 MS specs. This creates a new dataset using only top 10 specs

In [10]:
d = np.array([[1, 6], [2, 4], [3, 9], [-1, -4], [-2, 0], [-899, -999], [-999, -55]])
print(d)
print(np.argpartition(d, -3, 0))
print(d[np.argpartition(d[:,1], -3)])

[[   1    6]
 [   2    4]
 [   3    9]
 [  -1   -4]
 [  -2    0]
 [-899 -999]
 [-999  -55]]
[[4 5]
 [6 6]
 [5 3]
 [3 4]
 [0 1]
 [1 2]
 [2 0]]
[[-899 -999]
 [-999  -55]
 [  -1   -4]
 [  -2    0]
 [   2    4]
 [   3    9]
 [   1    6]]


In [19]:
def shatter_small_ms(shatter_dir, obj, id, keys):
    '''
        Saves an object as individual files

        <dataset_type>
            - <split>
                - <key>
                    - id.pt

        Parameters
        -----------
        shatter_dir: directory to place file into. <dataset_type>/<split>
        obj: the object to split
        id: the id that colin assigned to the sample
        keys: the feature directories to assign
    '''
    for key in keys: # FP, SMILES, etc.
        elem = obj[key]
        if key == "MS" and len(elem) > 10:
            # gets indexes of 10 highest items by intensity. Everything from [-10:,1] will be indexes
            # of things with a higher intensity than the 10'th highest intensity
            partition = np.argpartition(elem, -10, axis=0)[-10:,1]
            elem = elem[partition]

        if type(elem) == np.ndarray:
            torch.save(torch.tensor(elem, dtype=torch.float), f"{shatter_dir}/{key}/{id}.pt")
        elif type(elem) == str:
            torch.save(elem, f"{shatter_dir}/{key}/{id}.pt")

In [20]:
files = glob.glob("../../tempdata/data/*/*.pkl") # glob files from colin_split_05_03_22
out_dir = "../../tempdata/smaller_ms"
os.makedirs(out_dir, exist_ok=True)
save_attrs = {
    "hsqc_ms_pairs": ["SMILES", "FP", "HYUN_FP", "HSQC", "MS"],
    "hsqc_pretrain": ["SMILES", "FP", "HYUN_FP", "HSQC"],
    "ms_pretrain": ["SMILES", "FP", "HYUN_FP", "MS"]
}
for file_path in files:
    subdivision = file_path.split("/")[-2] # one of hsqc_ms_pairs, hsqc_pretrain, ms_pretrain
    split = file_path.split("/")[-1] # one of train, val, test
    split = split[:split.index(".")]

    for my_attr in save_attrs[subdivision]:
        os.makedirs(f"{out_dir}/{subdivision}/{split}/{my_attr}", exist_ok=True)

    print(file_path, subdivision, split)
    with open(file_path, "rb") as f:
        obj = pickle.load(f)

    keys = set(obj.keys()) # list of id's
    for k in keys:
        v = obj[k]
        v["HYUN_FP"] = fingerprint_utils.FP_generator(v["SMILES"], 2)
        shatter_small_ms(f"{out_dir}/{subdivision}/{split}", v, k, save_attrs[subdivision])
        del obj[k]

../../tempdata/data/hsqc_ms_pairs/train.pkl hsqc_ms_pairs train


[06:50:54] WARNING: not removing hydrogen atom without neighbors


../../tempdata/data/hsqc_ms_pairs/val.pkl hsqc_ms_pairs val
../../tempdata/data/hsqc_ms_pairs/test.pkl hsqc_ms_pairs test
../../tempdata/data/hsqc_pretrain/train.pkl hsqc_pretrain train


[06:52:13] WARNING: not removing hydrogen atom without neighbors
[06:52:19] WARNING: not removing hydrogen atom without neighbors
[06:52:22] WARNING: not removing hydrogen atom without neighbors
[06:52:38] WARNING: not removing hydrogen atom without neighbors
[06:52:47] WARNING: not removing hydrogen atom without neighbors
[06:53:43] WARNING: not removing hydrogen atom without neighbors
[06:54:19] WARNING: not removing hydrogen atom without neighbors
[06:55:34] WARNING: not removing hydrogen atom without neighbors
[06:56:11] WARNING: not removing hydrogen atom without neighbors
[06:57:18] WARNING: not removing hydrogen atom without neighbors


../../tempdata/data/hsqc_pretrain/val.pkl hsqc_pretrain val


[06:58:32] WARNING: not removing hydrogen atom without neighbors
[06:58:46] WARNING: not removing hydrogen atom without neighbors


../../tempdata/data/hsqc_pretrain/test.pkl hsqc_pretrain test


[06:59:31] WARNING: not removing hydrogen atom without neighbors
[06:59:31] WARNING: not removing hydrogen atom without neighbors


../../tempdata/data/ms_pretrain/train.pkl ms_pretrain train
../../tempdata/data/ms_pretrain/val.pkl ms_pretrain val
../../tempdata/data/ms_pretrain/test.pkl ms_pretrain test
