In [1]:
import sys, torch
sys.path.insert(0, '../../utils')
import ranker

In [2]:
data = torch.tensor([
    [0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 1],
    [0, 0, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1],
], dtype=torch.float)
rs = ranker.RankingSet(store=data, debug=True)

In [3]:
queries = torch.tensor([[0, 0, 0, 0, 0, 1]], dtype=torch.float)
truth = torch.tensor([[0, 0, 1, 1, 1, 1]], dtype=torch.float)

out = rs.batched_rank(queries, truth)
print(out)

tensor([[0.0000],
        [0.7071],
        [0.5000],
        [0.4082]])
tensor([[0.0000],
        [0.7071],
        [1.0000],
        [0.8165]])
tensor([0.5000])
tensor([False, False,  True, False])
tensor([False,  True,  True, False])
tensor([1.])


In [10]:
import numpy as np
ct_flip = 20
rs = ranker.RankingSet(file_path="../../tempdata/hyun_pair_ranking_set_07_22/test_pair.pt")
query = torch.zeros((1, 6144), dtype=torch.float)
true = torch.zeros((1, 6144), dtype=torch.float)

idxs = np.random.choice(range(6144), ct_flip, replace=False)
idxs2 = np.random.choice(range(6144), ct_flip, replace=False)
query[0,idxs] = 1- query[0,idxs]
true[0,idxs2] = 1- true[0,idxs2]
out = rs.batched_rank(query, true)
print(out)

tensor([1205.])
