# 03/15/23 Testing a graycode encoder

In [3]:
import graycode, torch
%load_ext autoreload
%autoreload 2

In [14]:
v = graycode.tc_to_gray_code(1)
print(v, bin(v))

1 0b1


In [53]:
mask = 2**torch.arange(15)[None, None, :]
print(mask.size())

torch.Size([1, 1, 15])


In [47]:
def do_graycode(x, bufsize, resolution):
  buf = torch.zeros(bufsize, dtype=torch.int)
  x_adj = torch.tensor(x / resolution).int()
  bits = 1 if abs(x) < 1e-8 else int(torch.log2(x_adj).floor()) + 1
  mask = 2**torch.arange(bits).int()
  bit_res = x_adj.bitwise_and(mask).ne(0)
  buf[:bits] = bit_res
  return buf
  # return x.unsqueeze(-1).bitwise_and(mask).ne(0).byte()
for v in torch.arange(1, 140):
  binary(v, 0.1)

tensor(1) 10 4
tensor([0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)
tensor(2) 20 5
tensor([0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)
tensor(3) 30 5
tensor([0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)
tensor(4) 40 6
tensor([0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)
tensor(5) 50 6
tensor([0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)
tensor(6) 60 6
tensor([0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)
tensor(7) 70 7
tensor([0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)
tensor(8) 80 7
tensor([0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)
tensor(9) 90 7
tensor([0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)
tensor(10) 100 7
tensor([0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)
tensor(11) 110 7
tensor([0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)
tensor(12) 120 7
tensor([0, 

/tmp/ipykernel_7897/2345565508.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x_adj = torch.tensor(x / resolution).int()


In [2]:
from datasets.generic_index_dataset import GenericIndexedModule
from datasets.dataset_utils import pad
from models.identity_module import IdentityModule
from pathlib import Path
import os, pytorch_lightning as pl
import torch

In [5]:
direct = Path("tempdata/SMILES_dataset")
features = ["HSQC", "HYUN_FP"]
feature_handlers = [pad, None]
gim = GenericIndexedModule(direct, features, feature_handlers, len_override = 5)
gim.setup("fit")
model = IdentityModule()
tr_dl = gim.train_dataloader()
val_dl = gim.val_dataloader()

In [8]:
for batch in tr_dl:
  hsqc, _ = batch
  print(hsqc[2])
  break

tensor([[ 1.3680e+02,  5.7058e+00,  6.9806e+03],
        [ 1.2870e+02,  7.1929e+00,  1.5757e+04],
        [ 1.2805e+02,  7.3701e+00,  6.9822e+03],
        [ 1.2706e+02,  7.2030e+00,  5.4609e+03],
        [ 1.1732e+02,  5.2428e+00, -3.4911e+03],
        [ 1.1732e+02,  5.0495e+00, -5.9105e+03],
        [ 1.1433e+02,  6.6775e+00,  6.9806e+03],
        [ 6.4020e+01,  3.3308e+00, -8.7365e+03],
        [ 6.4020e+01,  3.0242e+00, -5.7486e+03],
        [ 5.9850e+01,  3.0122e+00, -6.3924e+03],
        [ 5.9850e+01,  2.9872e+00, -5.0655e+03],
        [ 5.5400e+01,  3.4011e+00, -7.7193e+03],
        [ 5.5400e+01,  3.3711e+00, -5.0655e+03],
        [ 4.4170e+01,  4.3621e+00,  4.7581e+03],
        [ 3.2630e+01,  3.1321e+00, -6.9805e+03],
        [ 3.2630e+01,  2.8483e+00, -8.7769e+03],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00