In [1]:
import numpy as np, torch, os, pickle
import imp
smart = imp.load_source('/root/gurusmart/MorganFP_prediction/reproduce_previous_works/smart4.5/datasets/', '/root/gurusmart/MorganFP_prediction/reproduce_previous_works/smart4.5/datasets/dataset_utils.py')
    
    
    
    



/tmp/ipykernel_1691/2642187582.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import imp


In [3]:
for i in range(1,16):
    builder = smart.Specific_Radius_MFP_loader()
    builder.setup()
    builder.set_max_radius(i)
    print(f"fingerprint R0-to-R{i}, entropy of each bit is {-builder.entropy/6144 :.4f}")
    # print(builder.__entropy)
    # break

fingerprint R0-to-R1, entropy of each bit is 0.0181
fingerprint R0-to-R2, entropy of each bit is 0.0582
fingerprint R0-to-R3, entropy of each bit is 0.0959
fingerprint R0-to-R4, entropy of each bit is 0.1259
fingerprint R0-to-R5, entropy of each bit is 0.1496
fingerprint R0-to-R6, entropy of each bit is 0.1687
fingerprint R0-to-R7, entropy of each bit is 0.1849
fingerprint R0-to-R8, entropy of each bit is 0.1988
fingerprint R0-to-R9, entropy of each bit is 0.2111
fingerprint R0-to-R10, entropy of each bit is 0.2222
fingerprint R0-to-R11, entropy of each bit is 0.2322
fingerprint R0-to-R12, entropy of each bit is 0.2414
fingerprint R0-to-R13, entropy of each bit is 0.2499
fingerprint R0-to-R14, entropy of each bit is 0.2578
fingerprint R0-to-R15, entropy of each bit is 0.2653


In [4]:
3/4

0.75

In [3]:
val_2d_path  = '/workspace/SMILES_dataset/val/R0_to_R4_reduced_FP/'
val_2d_files = os.listdir(val_2d_path)
# val_2d_files[:10]

In [4]:
import torch
from pathlib import Path
builder.set_max_radius(4,only_2d=True)
built_rankingset = builder.build_rankingset('2d', 'val')
load_rankingset = torch.load('/workspace/ranking_sets_cleaned_by_inchi/SMILES_R0_to_R4_reduced_FP_ranking_sets/val/rankingset.pt')
    

print all input:  [  0.  10.   0. ... 503. 843. 856.] 109793 6144 True
[-0.36787911 -0.36786846 -0.36785804 ... -0.04420198 -0.04420198
 -0.04416866]


In [5]:
load_rankingset.shape, built_rankingset.shape

(torch.Size([11151, 6144]), torch.Size([11151, 6144]))

In [6]:
load_rankingset == built_rankingset

tensor([[ True,  True,  True,  ...,  True,  True,  True],
        [ True,  True,  True,  ...,  True,  True,  True],
        [ True,  True,  True,  ...,  True,  True,  True],
        ...,
        [False, False, False,  ...,  True,  True,  True],
        [False, False, False,  ...,  True,  True,  True],
        [False, False, False,  ...,  True,  True,  True]])

In [7]:
(load_rankingset.sum(dim=0) == built_rankingset.sum(dim=0)).all()

tensor(True)

In [8]:
load_rankingset.sum(dim=0).shape

torch.Size([6144])

In [20]:
(load_rankingset.sum(dim=0))

tensor([3903., 3937., 3948.,  ...,  113.,   91.,   95.])

In [14]:
load_rankingset == built_rankingset

tensor([[ True,  True,  True,  ...,  True,  True,  True],
        [ True,  True,  True,  ...,  True,  True,  True],
        [ True,  True,  True,  ...,  True,  True,  True],
        ...,
        [False, False, False,  ...,  True,  True,  True],
        [False, False, False,  ...,  True,  True,  True],
        [False, False, False,  ...,  True,  True,  True]])